# Welcome to Jekyll!

minimal_mistakes_skin    : "default"

# Site Settings
locale                   : "en-US"
title                    : "Site Title"
title_separator          : "-"
name                     : "Your Name"
description              : "An amazing website."

# Navigation Tabs
navigation:
  - title: "Home"
    url: "/"
  - title: "AI Products"
    url: "/ai-products/"
  - title: "Physical Products"
    url: "/physical-products/"
  - title: "Others"
    url: "/others/"

# Author Info
author:
  name             : "Your Name"
  bio              : "I am an **amazing** person."
  location         : "Somewhere"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
    - label: "Website"
      icon: "fas fa-fw fa-link"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"

# Footer Social Links
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
    - label: "Bitbucket"
      icon: "fab fa-fw fa-bitbucket"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"

include:
  - .htaccess
  - _pages

exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - minimal-mistakes-jekyll.gemspec
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs
  - /test

keep_files:
  - .git
  - .svn

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Markdown and Sass
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed

# Output
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/

# Pagination with jekyll-paginate-v2
pagination:
  debug: false
  collection: 'posts'
  per_page: 10
  permalink: '/page/:num/'
  title: ':title - page :num'
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  trail:
    before: 2
    after: 2

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Defaults for posts
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
